package script.template

import client.MapleClient
import server.maps.MapleReactor
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

class AutoGeneratedReactorScriptTemplate(r: MapleReactor, c: MapleClient) {

    /**
     * A lot of reactors just drop items and that info is stored in the database.
     * Some need additional assistance so that is why we generate a script for
     * them just in case.
     */

    var reactor = r
    var client = c
    var path = "./scripts/reactor/"
    var df = SimpleDateFormat("yyyy-MM-dd")
    private var date: String = df.format(Date())

    private val scriptHeader = """/*
    This is an auto-generated reactor script for Boswell!
    
    Reactor Name: ${reactor.name}   
    Reactor Id: ${reactor.id}
    Reactor Type: ${reactor.reactorType}
    Reactor Position: ${reactor.position}
    Location Name: ${reactor.map.mapName}
    Location ID: ${reactor.map.id}
            
    @Author: Auto Generated
    @Created: $date 
    */
    """

    private val scriptContents = "" //todo

    fun create() {
        val fileName = "$path${reactor.name}.groovy"
        val newFile = File(fileName)

        if (newFile.createNewFile()) {
            val fw = FileWriter(newFile)
            fw.append(scriptHeader)
            fw.append(scriptContents)
            fw.close()
        }
    }
}