package script.template

import client.MapleClient
import client.MapleQuestStatus
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

class AutoGeneratedQuestScriptTemplate(
    private val questStatus: MapleQuestStatus,
    private val client: MapleClient,
    private val name: String
) {

    private val path = "./scripts/quest/"
    private val df = SimpleDateFormat("yyyy-MM-dd")
    private val date: String = df.format(Date())

    private val scriptHeader = """/*
    This is an auto-generated quest script for Boswell!
    
    Quest Name: ${questStatus.quest.name}            
    Quest ID: ${questStatus.quest.id}
    Location Name: ${client.player.map.mapName}
    Location ID: ${client.player.mapId}
    
    Parent Quest Name: ${questStatus.quest.parentName}
    Repeatable?: ${questStatus.quest.isSameDayRepeatable}
    Time Limit?: ${questStatus.quest.timeLimit}
    Relevant Mobs: ${questStatus.quest.relevantMobs}
            
    @Author: Auto Generated
    @Created: $date 
    */
    """
    private val scriptContents = """
    user.message("A script file has been generated for this quest. However, the quest does not currently work.")
    """

    fun create() {
        val fileName = "$path$name.groovy"
        val newFile = File(fileName)

        if (newFile.createNewFile()) {
            val fw = FileWriter(newFile)
            fw.append(scriptHeader)
            fw.append(scriptContents)
            fw.close()
        }
    }
}