package script.template

import server.maps.MapleMap
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

class AutoGeneratedFieldScriptTemplate(private val field: MapleMap, private val name: String, firstUser: Boolean) {
    /**
     * This handles both the creation of onUserEnter and onFirstUserEnter scripts,
     * so it's a little more complex than the other templates. With these scripts
     * you can perform actions when users travel to specific fields.
     */

    private val path = "./scripts/field"
    private val scriptType = if (firstUser) "onFirstUserEnter" else "onUserEnter"
    private val modifiedPath = "$path/$scriptType"
    private val df = SimpleDateFormat("yyyy-MM-dd")
    private val date: String = df.format(Date())

    private val scriptHeader = """
        /*
        This is an auto-generated field script for Boswell!
        
        Script Name: ${field.onUserEnter}
        Field Name: ${field.mapName}   
        Field Id: ${field.id}
        Script Type: $scriptType
                
        @Author: Auto Generated
        @Created: $date 
        */
    """

    private val scriptContents = """user.message("A script file has been generated for this field. 
        However, the field ($scriptType) script does not currently work.")"""

    fun create() {
        val fileName = "$modifiedPath/$name.groovy"
        val newFile = File(fileName)

        if (newFile.createNewFile()) {
            FileWriter(newFile).use {
                it.append(scriptHeader)
                it.append(scriptContents)
            }
        }
    }
}