package script.template

import client.MapleClient
import server.life.MapleLifeFactory
import server.life.MapleNPC
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

class AutoGeneratedNpcScriptTemplate(
    private val npc: MapleNPC,
    private val client: MapleClient,
    private val name: String? = null
) {
    private val path = "./scripts/npc/"
    private val defaultTalk: String = MapleLifeFactory.getNPCDefaultTalk(npc.id)
    private val df = SimpleDateFormat("yyyy-MM-dd")
    private val date: String = df.format(Date())

    private val scriptHeader = """/*
    This is an auto-generated NPC script for Boswell!
    
    Npc Name: ${npc.templateName}            
    Npc ID: ${npc.id}
    Location Name: ${client.player.map.mapName}
    Location ID: ${client.player.mapId}
            
    @Author: Auto Generated
    @Created: $date 
    */
    """

    private val scriptContents = """script.say("$defaultTalk")"""

    fun create() {
        val fileName = "${path}${name ?: npc.templateName}.groovy"
        val newFile = File(fileName)

        if (newFile.createNewFile()) {
            val fw = FileWriter(newFile)
            fw.append(scriptHeader)
            fw.append(scriptContents)
            fw.close()
        }
    }
}