package script.template

import client.MapleClient
import server.MapleItemInformationProvider.ScriptedItem
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

class AutoGeneratedItemScriptTemplate(private val item: ScriptedItem, private val client: MapleClient) {

    private val path = "./scripts/item/"
    private val df: SimpleDateFormat = SimpleDateFormat("yyyy-MM-dd")
    private val date: String = df.format(Date())

    private val scriptHeader = """/*
    This is an auto-generated Item script for Boswell!
    
    ScriptName: ${item.script}            
    NPC Involved: ${item.npc}
    Location Name: ${client.player.map.mapName}
    Location ID: ${client.player.mapId}
            
    @Author: Auto Generated
    @Created: $date 
    */
    """

    private val scriptContents = """
    user.message("A script file has been generated for this quest. However, the quest does not currently work.")
    """

    fun create() {
        val fileName = "$path${item.script}.groovy"
        val newFile = File(fileName)

        if (newFile.createNewFile()) {
            val fw = FileWriter(newFile)
            fw.append(scriptHeader)
            fw.append(scriptContents)
            fw.close()
        }
    }

}