package script

import client.MapleClient
import server.life.MapleLifeFactory
import server.life.MapleNPC
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*


class AutoGeneratedNpcScriptTemplate(n: MapleNPC, c: MapleClient, script: String?) {
    var npc = n
    var client = c
    var name = script
    var path = "./scripts/npc/"
    private var defaultTalk: String = MapleLifeFactory.getNPCDefaultTalk(npc.id)
    var df = SimpleDateFormat("yyyy-MM-dd")
    private var date: String = df.format(Date())

    private val scriptHeader = """/*
    This is an auto-generated NPC script for Boswell!
    
    Npc Name: ${npc.templateName}            
    Npc ID: ${npc.id}
    Location Name: ${client.player.map.mapName}
    Location ID: ${client.player.mapId}
            
    @Author: Auto Generated
    @Created: $date 
    */
    """

    private val scriptContents = "npc.say(\"$defaultTalk\")"

    fun create() {
        val fileName = "$path$name.groovy"
        val newFile = File(fileName)

        if (newFile.createNewFile()) {
            val fw = FileWriter(newFile)
            fw.append(scriptHeader)
            fw.append()
            fw.append(scriptContents)
            fw.close()
        }
    }
}